version: "3.3"

services:
  fah0:
    image: foldingathome/fah-gpu:latest
    user: 1000:1000
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: "8000M"
    volumes:
      - ${HOME}/banano-at-home/fah:/fah
        
